sudo: required
dist: trusty
matrix:
  include:
    - language: java
      before_install: 
       - chmod +x mvnw
       - chmod +x build.sh
      script: ./build.sh
    - language: node_js
      before_install:
       - chmod +x ./TravisDemo/build.sh
       - npm install -g @angular/cli
       - cd ./TravisDemo
      script: ./TravisDemo/build.sh